// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using net8_rules_engine.Contexts;

#nullable disable

namespace net8_rules_engine.Migrations
{
    [DbContext(typeof(DataDbContext))]
    [Migration("20240421102502_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("net8_rules_engine.Models.Entities.DataEngine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_date")
                        .HasColumnOrder(3);

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_date")
                        .HasColumnOrder(4);

                    b.Property<int>("Vloop")
                        .HasColumnType("integer")
                        .HasColumnName("v_loop")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.ToTable("data_engine");
                });

            modelBuilder.Entity("net8_rules_engine.Models.Entities.VersionEngine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_date")
                        .HasColumnOrder(1);

                    b.HasKey("Id");

                    b.ToTable("version_engine");
                });

            modelBuilder.Entity("net8_rules_engine.Models.Entities.VersionEngineDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<string>("EngineCode")
                        .HasColumnType("text")
                        .HasColumnName("engine_code")
                        .HasColumnOrder(2);

                    b.Property<Guid?>("VersionEngineId")
                        .HasColumnType("uuid")
                        .HasColumnName("version_engine_id")
                        .HasColumnOrder(1);

                    b.HasKey("Id");

                    b.HasIndex("VersionEngineId");

                    b.ToTable("version_engine_detail");
                });

            modelBuilder.Entity("net8_rules_engine.Models.Entities.VersionEngineDetail", b =>
                {
                    b.HasOne("net8_rules_engine.Models.Entities.VersionEngine", null)
                        .WithMany("Details")
                        .HasForeignKey("VersionEngineId");
                });

            modelBuilder.Entity("net8_rules_engine.Models.Entities.VersionEngine", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
